# Деплой клиентской части

# Secrets
# - SSH_PRIVATE_KEY
# - SSH_USER
# - SSH_HOST
# - PROJECT_PATH

name: CI

# Запуск при пуше и слиянии в main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Мануальный запуск CI
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Настройка подключения через SSH
      - name: Setting up an SSH connection
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
      # Добавление хоста сервера
      - name: Adding a server host
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      
      ## Обновление локального репозитория на сервере
      - name: Getting project code via git
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.PROJECT_PATH }}/server && git checkout main && git pull"
          
      ## Сборка docker-образа
      - name: Building the docker image
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.PROJECT_PATH }} && ./build-client.sh"
          
      ## Рестарт docker-compose
      - name: Restarting docker-compose
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.PROJECT_PATH }} && ./run.sh"
